config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  resources :groups_users
  resources :orders
  resources :friends
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"


  get '/orders/new' => 'orders#new'
  post '/orders' => 'orders#create', as: 'newOrder'

  #after submitting new order, redirect to its details page
  get '/orders/details/:id' => 'meals#details', as: 'details'
  post '/orders/details/:id' => 'meals#addMeal', as: 'addMeal'

  # After creating order, redirect to invite friends page
  get '/orders/invite/:id' => 'orders#inviteFriends', as: 'inviteFriends'
  post '/orders/invite/:id' => 'orders#invite', as: 'invite'
  delete '/orders/invite/:id' => 'orders#cancel', as: 'cancel'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  validates :orderType, presence: true
  validates :resturant, presence: true

  belongs_to :user
  has_and_belongs_to_many :users
  has_one_attached :menu
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.where(user_id: current_user.id)
    p @orders
    @invites = Invite.where(user_id: current_user.id)
    p @invites
    @orders_from_invitations = []
    @invites.each do |invite|
      @orders_from_invitations.append(Order.where(id: invite.order_id).first)
    end
    p @orders_from_invitations

    @orders.each do |order|
      @orders_from_invitations.append(order)
    end

    p @orders_from_invitations

      # @orders_from_invitations = @orders_from_invitations.reorder('created_at DESC')
    
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    if (@order.save)
      redirect_to inviteFriends_path(@order)
    else
      render 'new'
    end
  end

  def inviteFriends
    @friends_arr = []
    current_user.friendships.each do |friendship|
      @friendsToInvite = @friends_arr.push(User.find(id = friendship.friend_id))
    end

    @groups = Group.where(creator: current_user.id)
    @invited_arr = []
    @order = Order.find(id = params['id'])
    @invite = Invite.where(order_id: @order.id)
    @invite.each do |invitation|
      @invitedFriends = @invited_arr.push(User.find(id = invitation.user_id))
    end

    @joined_arr = []
    @joined = Invite.where(order_id: @order.id, joined: true)
    @joined.each do |invitation|
      @joinedFriends = @joined_arr.push(User.find(id = invitation.user_id))
    end
  end

  def cancel
    @cancel_id = params["cancel-btn"]
    @order = Order.find(id = params['id'])
    @invite = Invite.where(order_id: @order.id)
    p 'cancel id ====', @cancel_id
    if not @cancel_id.nil?
      p params
      @deleted_invitation = @invite.where(user_id: @cancel_id)
      @deleted_invitation.delete_all
    end
    redirect_to inviteFriends_path
  end

  def invite
    @friend_id = params['invite-btn']
    @friend = User.find(id = @friend_id)
    @order = Order.find(id = params['id'])

    if Invite.where(user_id: @friend.id, order_id: @order.id).present?
      flash[:danger] = "#{@friend.first_name} is already invited"
      redirect_to inviteFriends_path
    elsif @new_invite = Invite.new()
      @new_invite.user = @friend
      @new_invite.order = @order
      if @new_invite.save
        Notification.create recipient_id: @friend.id, actor_id: current_user.id, action: "invited you to <a href=\"/orders/details/#{@order.id}\">#{@order.orderType}</a> at #{@order.resturant}.", category: 2, model: "orders"

      end
      redirect_to inviteFriends_path
    end
  end

  def cancel_order
    @order_id = params[:id]
    @order = Order.find(id = @order_id)
    @order.status = "Canceled"
    @order.save
    redirect_to orders_path
  end


  def inviteGroup
    @group_id = params["inviteGroup-btn"]
    @order = Order.find(id = params['id'])
    @groupToInvite = Group.find_by(id: @group_id)
    @groupToInvite_members = @groupToInvite.users.all

    @groupToInvite_members.each do |user|
      if Invite.where(user_id: user.id, order_id: @order.id).present?
        flash[:danger] = "#{user.first_name} is already invited"
      elsif @new_invite = Invite.new()
        @new_invite.user = user
        @new_invite.order = @order
        @new_invite.save
      end
    end
    redirect_to inviteFriends_path
  end

  def finish
    @order_id = params[:id]
    @order = Order.find(id = @order_id)
    @order.status = "Finished"
    @order.save
    redirect_to orders_path
  end

  private def order_params
    params.require(:newOrder).permit(:orderType, :resturant, :menu)
  end

  def accept

    #Notification.find()
    redirect_to '/orders'
  end

  def decline

  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true, :authenticity_token => true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= text_field_tag(:type, placeholder: "Order type", class: "form-control") %>
  </div>
  <div>
    <label for="restaurant" class="col-3">Restaurant:</label>
    <input type="text" name="restaurant" id="" class="col-7">
  </div>
<!--  <div class="input-group">-->
    <%#= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
<!--    <div class="input-group-btn">-->
      <%#= button_tag "test", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
<!--    </div>-->
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%#= simple_form_for @order, url: orders_path do |f| %>
  <%#= f.input :type, @order.type %>
  <%#= f.input :restaurant, @order.restaurant %>
  <%#= f.input :Menu, as: :file %>
  <%#= f.association :friends %>
  <%#= f.submit "Next", class: 'btn btn-lg btn-primary float-right' %>
<%# end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="container bg-dark">
  <div class="row">
  
    <div class="col-md-4"></div>
<div class="col-md-4" style="margin: 10px;">
     <%= link_to "Start New Order", "/orders/new" , class: "btn btn-primary"%>
</div>
<div class="col-md-4"></div>
  </div>


  <table class="table table-dark">
    <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Order</th>
      <th scope="col">Resturant</th>
      <th scope="col">Invited</th>
      <th scope="col">Joined</th>
      <th scope="col">Status</th>
      <th scope="col" colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @orders_from_invitations.each do |order| %>
      <tr>
        <th scope="row"><%= order.id %></th>
        <td>
          <%= order.orderType %>
        </td>
        <td><%= order.resturant %></td>
        <td><%= @invites.count {|invite| invite.order_id == order.id } %></td>
        <td><%= @invites.count {|invite| (invite.order_id == order.id && invite.joined == true)} %></td>
        <td><%= order.status %></td>
        <td>
          <%= link_to "View", details_path(order) , class: "btn btn-primary" %>
        </td>
        <td>
          <%= link_to "Finish", finishOrder_path(order) , class: "btn btn-primary", method: "POST" %>
        </td>
        <td>
          <%= link_to "Cancel", cancelOrder_path(order) , class: "btn btn-primary", method: "POST" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/orders/inviteFriends.html.erb
<h1>Invite friends to Your order</h1>
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card " style="margin-top: 50px;">
        <div class="card-header">
          <b>Your Friends</b>
        </div>
        <div class="card-body">

          <%= form_for :invite, url: invite_url do |f| %>

            <% flash.each do |type, msg| %>
              <div class="alert alert-<%= type %> ">
                <%= msg %>
              </div>
            <% end %>

            <% unless @friendsToInvite.nil? %>
              <% @friendsToInvite.each do |friend| %>
                <div>
                  <div class="card-body">
                    <h5 class="card-title">
                      <%= "#{friend.first_name}  #{friend.last_name}" %>
                    </h5>
                    <p><%= friend.email %></p>

                    <%= f.button "Invite", action_name: 'orders#invite', name: "invite-btn", value: friend.id, class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <h4 class="text-center col-12">You have no friends yet.</h4>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card " style="margin-top: 50px;">
        <div class="card-header">
          <b>Your groups</b>
        </div>
        <div class="card-body">
          <%= form_for :inviteGroup, url: inviteGroup_url do |f| %>
          <% flash.each do |type, msg| %>
              <div class="alert alert-<%= type %> ">
                <%= msg %>
              </div>
            <% end %>
              <% unless @groups == [] %>
                  <% @groups.each do |group| %>                
                      <div>
                          <div class="card-body">
                              <h5 class="card-title"><%= group.name %></h5>                    
                              <% group.users.all.each do |user| %>
                                  <p>
                                  <h6><%= "#{user.first_name}  #{user.last_name}" %></h6>
                                  </p>
                              <% end %>
                              <%= f.button 'Invite Group', action_name: 'orders#inviteGroup', name: "inviteGroup-btn", value: group.id, class: "btn btn-primary" %>
                          </div>
                      </div>
                  <% end %>
              <% else %>
                  <h4 class="text-center col-12">You have no groups</h4>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card " style="margin-top: 50px;">
        <div class="card-header">
          <b>Invited friends</b>
        </div>
        <div class="card-body">

          <%= form_for :cancel, url: cancel_path, method: :delete do |f| %>
            <% unless @invitedFriends.nil? %>
              <% @invitedFriends.each do |friend| %>
                <div>
                  <div class="card-body">
                    <h5 class="card-title">
                      <%= "#{friend.first_name}  #{friend.last_name}" %>
                    </h5>
                    <p><%= friend.email %></p>

                    <%= f.button "Cancel", action_name: 'orders#cancel', name: "cancel-btn", value: friend.id, class: "btn btn-danger" %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <h4 class="text-center col-12">You haven't invited any friends yet.</h4>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>
    <div class="col">
    <div class="card " style="margin-top: 50px;">
        <div class="card-header">
          <b>Joined friends</b>
        </div>
        <div class="card-body">
        
            <% unless @joinedFriends.nil? %>
              <% @joinedFriends.each do |friend| %>
                <div>
                  <div class="card-body">
                    <h5 class="card-title">
                      <%= "#{friend.first_name}  #{friend.last_name}" %>
                    </h5>
                    <p><%= friend.email %></p>

                  </div>
                </div>
              <% end %>
            <% else %>
              <h4 class="text-center col-12">No friends have Joined yet.</h4>
            <% end %>
          
        </div>
        </div>
    </div>
  </div>
</div>
<br>
<%= link_to "Add Order Details", details_path, {:class => "btn btn-primary active", :style => "margin-bottom:3cm; display:block;"} %>

app/views/orders/new.html.erb
<h1>Add Order</h1>

<div class="container">
  <div class="row">
    <div class="col">
      <%= form_for :newOrder, url: newOrder_url do |f| %>

        <% if @order.errors.any? %>
          <% @order.errors.full_messages.each do |msg| %>
              <div class="alert alert-danger"><%= msg %></div>
          <% end %>    
        <% end %>
        
        <div class="form-group ">
          <%= f.label(:orderType, {:class => 'sr-only'}) %>
          <%= f.select :orderType, ['Breakfast', 'Lunch', 'Dinner'], {prompt: "Order for..."}, {class: "form-control", :style => 'margin-top: 100px; margin-bottom: 30px;'} %>
        </div>

        <div class="form-group ">
          <%= f.label(:resturant, {:class => 'sr-only'}) %>
          <%= f.text_field(:resturant, {:class => 'form-control', :placeholder => 'Restaurant', :style => 'margin-bottom: 30px;'}) %>
        </div>

        <div class="custom-file">
          <%= f.label(:menu, {:class => 'custom-file-label', :for => "menu"}) %>
          <%= f.file_field(:menu, {:id => "menu", :class => 'custom-file-input', :style => 'margin-bottom: 30px;'}) %>
        </div>

<!--        <div class="form-group">-->
<!--          <div class='input-group date' id='datetimepicker'>-->
<!--            <input type='text' class="form-control"/>-->
<!--            <span class="input-group-addon">-->
<!--              <span class="glyphicon glyphicon-calendar"></span>-->
<!--            </span>-->
<!--          </div>-->
<!--          <script type="text/javascript">-->
<!--              $('#datetimepicker').datetimepicker({-->
<!--                  locale: 'fr',-->
<!--                  sideBySide: true,-->
<!--                  format: "DD-MM-YYYY h:mm A"-->
<!--              });-->
<!--          </script>-->
<!--        </div>-->

        <%= f.button 'Publish', class: 'btn btn-primary mt-5', type: 'submit' %>

      <% end %>
    </div>


  </div>
</div>
</div>