config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  resources :groups_users
  resources :orders
  resources :friends
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"


  get '/orders/new' => 'orders#new'
  post '/orders' => 'orders#create', as: 'newOrder'

  #after submitting new order, redirect to its details page
  get '/orders/details/:id' => 'meals#details', as: 'details'
  post '/orders/details/:id' => 'meals#addMeal', as: 'addMeal'

  # After creating order, redirect to invite friends page
  get '/orders/invite/:id' => 'orders#inviteFriends', as: 'inviteFriends'
  post '/orders/invite/:id' => 'orders#invite', as: 'invite'
  delete '/orders/invite/:id' => 'orders#cancel', as: 'cancel'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence:true, uniqueness:true
  has_and_belongs_to_many :users
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :order
  belongs_to :user
end

app/models/meal.rb
class Meal < ApplicationRecord
    validates :meal, presence: true
    validates :amount, presence: true
    validates :price, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  #belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read_at: nil) }

end

app/models/order.rb
class Order < ApplicationRecord
  validates :orderType, presence: true
  validates :resturant, presence: true

  belongs_to :user
  has_and_belongs_to_many :users
  has_one_attached :menu
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friendships
  has_many :notifications, foreign_key: :recipient_id
  has_many :notifications, foreign_key: :actor_id

  has_one_attached :avatar
  has_and_belongs_to_many :orders
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.where(creator: current_user.id)
  end
  def show
    @groups = Group.where(creator: current_user.id)
    @group = Group.find_by(id: params[:id], creator: current_user.id)
    if @group.nil?
      flash[:group_error] = "No Group exists with this id"
      redirect_to :groups
    else
      @group_members = @group.users.all
    end
    
  end

  def create
    @group = Group.new
    @group.creator = current_user.id
    @group.name = params[:name]
    @group.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @group = Group.find params[:id]
    if @group.destroy
      flash[:delete_notice] = "Group successfully deleted"
      redirect_to groups_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   before_action :authenticate_user!

  def index
    orders = Order.where(user_id: current_user.id)
    p orders
    invites = Invite.where(user_id: current_user.id)
    p invites
    @orders_from_invitations = []
    invites.each do |invite|
      @orders_from_invitations.append(Order.where(id: invite.order_id).first)
    end
    p @orders_from_invitations

    orders.each do |order|
      @orders_from_invitations.append(order)
    end
    @orders_from_invitations = @orders_from_invitations[0..4]
    p @orders_from_invitations
  end

  def show
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def details
    @order = Order.where(id: params[:id]).first
    @meals = Meal.where(order: params[:id])
  end

  def addMeal
    @meal = Meal.new(meal_params)
    @meal.order = params[:id]
    if (@meal.save)
      @meals = Meal.where(order: params[:id])
      render 'details'
    else
      @meals = Meal.where(order: params[:id])
      render 'details'
    end
  end

  private def meal_params
    params.require(:addMeal).permit(:person, :meal, :amount, :price, :comment, :order)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @users = User.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/groups_users_helper.rb
module GroupsUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.erb
<!-- Site footer -->
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-3 col-md-6">
        <h6>About</h6>
        <p class="text-justify">
          YallNotlop, order food and invite your friends
        </p>
      </div>

      <div class="col-md-8 col-sm-2 col-xs-6">
        <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by
          <a href="#">(ITI - Students - Intake@40)</a>.
        </p>
      </div>

      <div class="col-md-4 col-sm-2 col-xs-6">
        <ul class="social-icons">
          <li><a class="facebook" href="#"><i class="fab fa-facebook"></i></a></li>
          <li><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
          <li><a class="dribbble" href="#"><i class="fab fa-dribbble"></i></a></li>
          <li><a class="linkedin" href="#"><i class="fab fa-linkedin"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yalanotlob</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>-->
</head>

<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "YallaNotlob", root_path, class: "navbar-brand" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Groups", groups_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Orders", "/orders/", class: "nav-link" %>
        </li>
      </ul>


      <% if user_signed_in? %>
        <!--        notification part-->

        <ul class="navbar-nav md-10">
          <li class="nav-item dropdown notifications" data-behavior="notifications">
            <a class="dropdown-toggle nav-link" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="">
              <span class="fa-stack has-badge" data-behavior="notifications-link">
                <i class="far fa-bell fa-2x"></i>
              </span>
            </a>
            <ul class="dropdown-menu notifications">
              <li class="head text-light bg-dark">
                <div class="row">
                  <div class="col-lg-12 col-sm-12 col-12">
                    <span data-behavior="notifications-count">Notifications (0)</span>
                    <a href="/notifications/mark_as_read" id="notifications-read" class="float-right text-light">Mark
                      all as read</a>
                    <%#= link_to "Mark all as read", '/notifications/mark_as_read', id: "notifications-read",class: "float-right text-light", :remote => true, method: :post %>
                  </div>
                </div>
              </li>
              <ul data-behavior="notification-items">
                <!--                              <li class="notification-box">-->
                <!--                                <div class="row">-->
                <!--                                  <div class="col-lg-3 col-sm-3 col-3 text-center">-->
                <!--                                    <img src="/demo/man-profile.jpg" class="w-50 rounded-circle">-->
                <!--                                  </div>-->
                <!--                                  <div class="col-lg-8 col-sm-8 col-8">-->
                <!--                                    <strong class="text-info">David John</strong>-->
                <!--                                    <div>-->
                <!--                                      Lorem ipsum dolor sit amet, consectetur-->
                <!--                                    </div>-->
                <!--                                    <div>-->
                <!--                                      <a href="">-->
                <!--                                        <button type="button" class="btn btn-success btn-sm">Accept</button>-->
                <!--                                      </a>-->
                <!--                                      <a href="">-->
                <!--                                        <button type="button" class="btn btn-danger btn-sm">Deny</button>-->
                <!--                                      </a>-->
                <!--                                    </div>-->
                <!--                                    <small class="text-warning">27.11.2015, 15:00</small>-->
                <!--                                  </div>-->
                <!--                                </div>-->
                <!--                              </li>-->

              </ul>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, width: "40", height: "40", class: "rounded-circle" %>
              <% else %>
                <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="40" height="40" class="rounded-circle">
              <% end %>
              <%= current_user.first_name %>
              <%= current_user.last_name %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <!--              <a class="dropdown-item" href="#">Dashboard</a>-->
              <!--              <a class="dropdown-item" href="#">Edit Profile</a>-->
              <p class="dropdown-item"> <%= current_user.email %></p>
              <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE">
                <i class="fas fa-sign-out-alt"></i>
                Log Out
              </a>
            </div>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>

<%= render "layouts/footer" %>

</html>